version: "3.8"

# Uncomment configs if you want to change the entrypoint or patroni config
configs:
  haproxy.cfg:
    file: haproxy.cfg
  # postgres.yml:
  #   file: postgres.yml
  # entrypoint.sh:
  #   file: entrypoint.sh

# Uncomment volumes if you want persistence
# volumes:
#   dbdata1:
#     driver: local
#   dbdata2:
#     driver: local
#   dbdata3:
#     driver: local

services:
  postgres:
    image: haproxy:2.2.14-alpine
    configs:
    - source: haproxy.cfg
      target: /usr/local/etc/haproxy/haproxy.cfg
    ports:
    - "5001:5000" # Postgres
    - "7001:7000" # HAProxy stats

  postgres1:
    image: spgcontrols/postgresql-patroni-raft:${VERSION:-latest}
    hostname: postgres1
    environment:
      PATRONI_RAFT_PARTNER_ADDRS: "'postgres2:2222','postgres3:2222'"
    # configs: &configs
    # - source: postgres.yml
    #   target: /app/postgres.yml
    # - source: entrypoint.sh
    #   target: /app/entrypoint.sh
    # volumes:
    # - type: volume
    #   source: dbdata1
    #   target: /app/data

  postgres2:
    image: spgcontrols/postgresql-patroni-raft:${VERSION:-latest}
    hostname: postgres2
    environment:
      PATRONI_RAFT_PARTNER_ADDRS: "'postgres1:2222','postgres3:2222'"
    # configs: *configs
    # volumes:
    # - type: volume
    #   source: dbdata2
    #   target: /app/data

  postgres3:
    image: spgcontrols/postgresql-patroni-raft:${VERSION:-latest}
    hostname: postgres3
    environment:
      PATRONI_RAFT_PARTNER_ADDRS: "'postgres1:2222','postgres2:2222'"
    # configs: *configs
    # volumes:
    # - type: volume
    #   source: dbdata3
    #   target: /app/data
